### ISSUE TITLE
Not Loading stopped playing files

### ISSUE THREAD

**Issue by marioandluigi878** [Kalejin/DCSB#13] opened 2018-02-14 10:26 UTC
Just stopped loading the program no error no nothing and for the sound files I got red dots and now just it won't load up at all

**Comment by Kalejin** [comment] 2018-02-14 10:51
Can you please mouse over those red dots? It should show a pop up with error message.

**Comment by marioandluigi878** [comment] 2018-02-14 11:12
I wish i could but the program isn't even loading up for me anymore which is such a shame because I really like this program too

**Comment by marioandluigi878** [comment] 2018-02-14 11:31
[config - Copy.txt](https://github.com/Kalejin/DCSB/files/1723739/config.-.Copy.txt)
Github doesn't like XML so I just quickly made it .txt

**Comment by Kalejin** [comment] 2018-02-14 11:51
Seems like the problem is in output device. Output device that has been set is not available anymore and application does not handle it.

I'll fix it, but for now you can try replacing 2 to 0 in following section of the config and run the app again.
```xml
...
<PrimaryOutputDevice>
    <Number>2</Number>
</PrimaryOutputDevice>
...
```

**Comment by marioandluigi878** [comment] 2018-02-14 11:54
That seemed to work.....

**Comment by Kalejin** [comment] 2018-02-14 12:00
Handling connecting and disconnecting output devices is buggy, so it'll happen again.
I'll reopen this to track me fixing this issue.

**Comment by Kalejin** [comment] 2018-03-26 07:50
Resolved in commit #0c9549e

**Closed by Kalejin** 2018-03-26 07:50 UTC
